name: Example of an action from marketplace
on:
  push:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  check-python-syntax:
    name: Check python syntax with marketplace action
    runs-on: ubuntu-latest
    steps:
      - name: Check-out
        uses: actions/checkout@v2
      - name: Python Syntax Checker
        uses: cclauss/Find-Python-syntax-errors-action@v0.2.0
