name: Job dependency
on:
  push:
    branches: [ main ]

jobs:
  job-ubuntu:
    name: Date on ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Check-out
        uses: actions/checkout@v2
      - name: print date
        run: date
  job-windows:
    name: Date on windows
    runs-on: windows-latest
    steps:
      - name: Check-out
        uses: actions/checkout@v2
      - name: print date
        run: date
  job-macos:
    name: Date on macos
    runs-on: macos-latest
    steps:
      - name: Check-out
        uses: actions/checkout@v2
      - name: print date
        run: date
  final:
    name: Final job
    runs-on: ubuntu-latest
    needs: [job-ubuntu, job-windows, job-macos]
    steps:
      - name: Check-out
        uses: actions/checkout@v2
      - name: print date
        run: date

