name: Use GitHub defined secrets
on:
  push:
    branches: [ main ]
jobs:
  list-s3:
    name: List s3 buckets
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2
      - name: List S3 buckets
        run: aws s3api list-buckets
